'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert(
      'Players',
      [
        {
          gomafiaId: 159,
          clubId: 196,
          nickname: 'Градиент',
          stars: 5,
          power: 75,
          costcoins: 176000,
          ismarket: true,
          costgems: 9490,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '159.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 820,
          clubId: 196,
          nickname: 'Шпагат',
          stars: 5,
          power: 66,
          costcoins: 170240,
          ismarket: true,
          costgems: 4690,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '820.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 999,
          clubId: 196,
          nickname: 'Unicef',
          stars: 5,
          power: 64,
          costcoins: 168960,
          ismarket: true,
          costgems: 4690,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '999.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 279,
          clubId: 196,
          nickname: '007',
          stars: 5,
          power: 55,
          costcoins: 163200,
          ismarket: true,
          costgems: 4690,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '279.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1409,
          clubId: 196,
          nickname: 'EZY BLACK',
          stars: 4,
          power: 57,
          costcoins: 61680,
          ismarket: true,
          costgems: 1790,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1409.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 993,
          clubId: 196,
          nickname: 'Арривидерчи',
          stars: 5,
          power: 59,
          costcoins: 165760,
          ismarket: true,
          costgems: 9490,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '993.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 67,
          clubId: 196,
          nickname: 'Стоников',
          stars: 4,
          power: 60,
          costcoins: 62400,
          ismarket: true,
          costgems: 1790,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '67.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 266,
          clubId: 196,
          nickname: 'BWDMoscow',
          stars: 5,
          power: 64,
          costcoins: 168960,
          ismarket: true,
          costgems: 9490,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '266.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1636,
          clubId: 196,
          nickname: 'h0wk',
          stars: 4,
          power: 55,
          costcoins: 61200,
          ismarket: true,
          costgems: 1790,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1636.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 20,
          clubId: 196,
          nickname: 'Адвокат',
          stars: 3,
          power: 54,
          costcoins: 10160,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '20.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 754,
          clubId: 196,
          nickname: 'Феномен',
          stars: 4,
          power: 57,
          costcoins: 61680,
          ismarket: true,
          costgems: 1790,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '754.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1955,
          clubId: 196,
          nickname: 'Богема',
          stars: 2,
          power: 38,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1955.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 224,
          clubId: 196,
          nickname: 'Бабочка',
          stars: 2,
          power: 45,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '224.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1551,
          clubId: 196,
          nickname: 'arye',
          stars: 3,
          power: 68,
          costcoins: 10720,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1551.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1087,
          clubId: 196,
          nickname: 'Хола',
          stars: 2,
          power: 39,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1087.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 573,
          clubId: 196,
          nickname: 'Жэ',
          stars: 2,
          power: 41,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '573.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1112,
          clubId: 196,
          nickname: 'Казанская',
          stars: 5,
          power: 45,
          costcoins: 64000,
          ismarket: true,
          costgems: 4690,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1112.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1435,
          clubId: 196,
          nickname: 'MSR',
          stars: 3,
          power: 51,
          costcoins: 10040,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1435.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1250,
          clubId: 196,
          nickname: 'Sonya Blade',
          stars: 2,
          power: 57,
          costcoins: 5140,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1250.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 169,
          clubId: 196,
          nickname: 'Dying Devil',
          stars: 3,
          power: 56,
          costcoins: 10240,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '169.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1546,
          clubId: 196,
          nickname: 'Fade',
          stars: 3,
          power: 53,
          costcoins: 10120,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1546.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1037,
          clubId: 196,
          nickname: 'Телепат',
          stars: 2,
          power: 55,
          costcoins: 5100,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1037.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 960,
          clubId: 196,
          nickname: 'Komorebi',
          stars: 2,
          power: 39,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '960.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 4590,
          clubId: 196,
          nickname: 'FEDRA',
          stars: 2,
          power: 34,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '4590.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 4472,
          clubId: 196,
          nickname: 'Муж',
          stars: 1,
          power: 51,
          costcoins: 2510,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '4472.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 989,
          clubId: 196,
          nickname: 'Монтана',
          stars: 1,
          power: 37,
          costcoins: 1000,
          ismarket: true,
          costgems: 279,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '989.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 142,
          clubId: 196,
          nickname: 'БВ',
          stars: 2,
          power: 49,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '142.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1858,
          clubId: 196,
          nickname: 'VIP',
          stars: 1,
          power: 38,
          costcoins: 1000,
          ismarket: true,
          costgems: 279,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1858.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1455,
          clubId: 196,
          nickname: 'Один',
          stars: 2,
          power: 55,
          costcoins: 5100,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1455.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1170,
          clubId: 196,
          nickname: 'Shade',
          stars: 2,
          power: 43,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1170.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 5133,
          clubId: 196,
          nickname: 'Амадей',
          stars: 2,
          power: 43,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '5133.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 958,
          clubId: 196,
          nickname: 'Красный Торнадо',
          stars: 3,
          power: 75,
          costcoins: 11000,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '958.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 6880,
          clubId: 196,
          nickname: 'Сакура_',
          stars: 2,
          power: 43,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '6880.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 4415,
          clubId: 196,
          nickname: 'Romanoff',
          stars: 1,
          power: 34,
          costcoins: 1000,
          ismarket: true,
          costgems: 279,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '4415.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 570,
          clubId: 196,
          nickname: 'Шейх',
          stars: 1,
          power: 38,
          costcoins: 1000,
          ismarket: true,
          costgems: 279,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '570.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1681,
          clubId: 196,
          nickname: 'Просто Толя',
          stars: 3,
          power: 43,
          costcoins: 4000,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1681.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1908,
          clubId: 196,
          nickname: 'Лила',
          stars: 1,
          power: 40,
          costcoins: 1000,
          ismarket: true,
          costgems: 279,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1908.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 6274,
          clubId: 196,
          nickname: 'Jeveksy',
          stars: 1,
          power: 38,
          costcoins: 1000,
          ismarket: true,
          costgems: 279,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '6274.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1380,
          clubId: 196,
          nickname: 'Murphy',
          stars: 2,
          power: 43,
          costcoins: 2000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '1380.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 7327,
          clubId: 196,
          nickname: 'Lucky Strike',
          stars: 1,
          power: 49,
          costcoins: 1000,
          ismarket: true,
          costgems: 279,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '7327.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2526,
          clubId: 196,
          nickname: 'Mrak',
          stars: 1,
          power: 52,
          costcoins: 2520,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '2526.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 6660,
          clubId: 196,
          nickname: 'Ультра',
          stars: 1,
          power: 36,
          costcoins: 1000,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '6660.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 5270,
          clubId: 196,
          nickname: 'Гробовщик,',
          stars: 2,
          power: 34,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '5270.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2505,
          clubId: 196,
          nickname: 'DОMINO',
          stars: 1,
          power: 25,
          costcoins: 1000,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '2505.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 986,
          clubId: 196,
          nickname: 'One',
          stars: 2,
          power: 40,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '986.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1109,
          clubId: 196,
          nickname: 'neWADA',
          stars: 1,
          power: 43,
          costcoins: 1000,
          ismarket: true,
          costgems: 279,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1109.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1237,
          clubId: 196,
          nickname: '_Moon_',
          stars: 2,
          power: 32,
          costcoins: 2000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '1237.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1378,
          clubId: 196,
          nickname: 'Студент',
          stars: 2,
          power: 46,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1378.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1578,
          clubId: 196,
          nickname: 'wavysha',
          stars: 2,
          power: 38,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1578.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1645,
          clubId: 196,
          nickname: 'Rap',
          stars: 1,
          power: 30,
          costcoins: 1000,
          ismarket: true,
          costgems: 279,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1645.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2187,
          clubId: 196,
          nickname: 'Огонёк',
          stars: 1,
          power: 32,
          costcoins: 1000,
          ismarket: true,
          costgems: 279,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '2187.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2256,
          clubId: 196,
          nickname: 'Holder',
          stars: 3,
          power: 33,
          costcoins: 4000,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '2256.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2704,
          clubId: 196,
          nickname: 'Leeroyka',
          stars: 2,
          power: 52,
          costcoins: 5040,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '2704.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2719,
          clubId: 196,
          nickname: 'Псих',
          stars: 2,
          power: 44,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '2719.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2745,
          clubId: 196,
          nickname: 'smKv',
          stars: 1,
          power: 34,
          costcoins: 1000,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '2745.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 3205,
          clubId: 196,
          nickname: 'Триббиани',
          stars: 2,
          power: 29,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '3205.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 3854,
          clubId: 196,
          nickname: 'Амарена',
          stars: 2,
          power: 28,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '3854.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 4046,
          clubId: 196,
          nickname: 'Адвокат77',
          stars: 2,
          power: 40,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '4046.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 4069,
          clubId: 196,
          nickname: 'Баритон',
          stars: 1,
          power: 36,
          costcoins: 1000,
          ismarket: true,
          costgems: 279,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '4069.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 4376,
          clubId: 196,
          nickname: 'Asperity',
          stars: 1,
          power: 31,
          costcoins: 1000,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '4376.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 4394,
          clubId: 196,
          nickname: 'Trickster',
          stars: 1,
          power: 36,
          costcoins: 1000,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '4394.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 4578,
          clubId: 196,
          nickname: 'Namiko',
          stars: 1,
          power: 38,
          costcoins: 1000,
          ismarket: true,
          costgems: 279,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '4578.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 4959,
          clubId: 196,
          nickname: 'Бант',
          stars: 1,
          power: 46,
          costcoins: 1000,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '4959.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 4995,
          clubId: 196,
          nickname: 'Мать,',
          stars: 2,
          power: 34,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '4995.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 5453,
          clubId: 196,
          nickname: ',ЗагадкА,',
          stars: 2,
          power: 37,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '5453.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 5966,
          clubId: 196,
          nickname: ',WellDone',
          stars: 1,
          power: 43,
          costcoins: 1000,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '5966.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 6092,
          clubId: 196,
          nickname: 'ДипломаT',
          stars: 2,
          power: 15,
          costcoins: 2000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '6092.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 6515,
          clubId: 196,
          nickname: 'Икигай',
          stars: 1,
          power: 27,
          costcoins: 1000,
          ismarket: true,
          costgems: 279,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '6515.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 6700,
          clubId: 196,
          nickname: 'Декарт',
          stars: 1,
          power: 33,
          costcoins: 1000,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '6700.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 349,
          clubId: 196,
          nickname: 'Юджин',
          stars: 2,
          power: 0,
          costcoins: 2000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '349.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1146,
          clubId: 196,
          nickname: 'Vicious',
          stars: 1,
          power: 45,
          costcoins: 1000,
          ismarket: true,
          costgems: 279,
          isOpen: true,
          cityId: 1,
          countryId: 1,
          picture: '1146.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2049,
          clubId: 196,
          nickname: 'Amélie',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '2049.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2160,
          clubId: 196,
          nickname: 'Sin',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '2160.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2909,
          clubId: 196,
          nickname: 'Лавандa',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '2909.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 3908,
          clubId: 196,
          nickname: 'Deadpool,',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '3908.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 4142,
          clubId: 196,
          nickname: 'Mark',
          stars: 2,
          power: 41,
          costcoins: 2000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '4142.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 5528,
          clubId: 196,
          nickname: 'RustyPizza',
          stars: 1,
          power: 66,
          costcoins: 2660,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '5528.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 5534,
          clubId: 196,
          nickname: 'Lova',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '5534.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 6089,
          clubId: 196,
          nickname: 'Aster',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '6089.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 6879,
          clubId: 196,
          nickname: 'Скаво',
          stars: 1,
          power: 32,
          costcoins: 1000,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '6879.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 7890,
          clubId: 196,
          nickname: 'Sultan',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 279,
          isOpen: false,
          cityId: 1,
          countryId: 1,
          picture: '7890.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1115,
          clubId: 32,
          nickname: 'РФ',
          stars: 5,
          power: 74,
          costcoins: 175360,
          costgems: 9490,
          picture: '1115.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1115,
          clubId: 32,
          nickname: 'РФ',
          stars: 5,
          power: 74,
          costcoins: 175360,
          ismarket: true,
          costgems: 9490,
          isOpen: true,
          picture: '1115.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1544,
          clubId: 32,
          nickname: 'Кэтти',
          stars: 5,
          power: 62,
          costcoins: 167680,
          ismarket: true,
          costgems: 9490,
          isOpen: true,
          picture: '1544.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1125,
          clubId: 32,
          nickname: 'Игрок 9',
          stars: 4,
          power: 64,
          costcoins: 63360,
          ismarket: true,
          costgems: 4690,
          isOpen: true,
          picture: '1125.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 218,
          clubId: 32,
          nickname: 'Гордон',
          stars: 5,
          power: 60,
          costcoins: 166400,
          ismarket: true,
          costgems: 9490,
          isOpen: true,
          picture: '218.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 258,
          clubId: 32,
          nickname: 'Флай',
          stars: 4,
          power: 51,
          costcoins: 60240,
          ismarket: true,
          costgems: 4690,
          isOpen: true,
          picture: '258.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1041,
          clubId: 32,
          nickname: 'Loki',
          stars: 5,
          power: 57,
          costcoins: 164480,
          ismarket: true,
          costgems: 9490,
          isOpen: true,
          picture: '1041.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 276,
          clubId: 32,
          nickname: 'Bellissima',
          stars: 3,
          power: 58,
          costcoins: 10320,
          ismarket: true,
          costgems: 1790,
          isOpen: true,
          picture: '276.png',
          cityId: 2,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 14,
          clubId: 32,
          nickname: 'Leo',
          stars: 4,
          power: 69,
          costcoins: 64560,
          ismarket: true,
          costgems: 4690,
          isOpen: true,
          picture: '14.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 964,
          clubId: 32,
          nickname: 'Шико',
          stars: 3,
          power: 59,
          costcoins: 10360,
          ismarket: true,
          costgems: 1790,
          isOpen: true,
          picture: '964.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 15,
          clubId: 32,
          nickname: 'Ардыльян',
          stars: 4,
          power: 63,
          costcoins: 63120,
          ismarket: true,
          costgems: 4690,
          isOpen: true,
          picture: '15.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 721,
          clubId: 32,
          nickname: 'Insight',
          stars: 4,
          power: 59,
          costcoins: 62160,
          ismarket: true,
          costgems: 4690,
          isOpen: true,
          picture: '721.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 255,
          clubId: 32,
          nickname: 'Загадка',
          stars: 2,
          power: 54,
          costcoins: 5080,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          picture: '255.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2463,
          clubId: 32,
          nickname: 'Джесс',
          stars: 3,
          power: 47,
          costcoins: 4000,
          ismarket: true,
          costgems: 1790,
          isOpen: true,
          picture: '2463.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 953,
          clubId: 32,
          nickname: 'ВМТ',
          stars: 3,
          power: 56,
          costcoins: 10240,
          ismarket: true,
          costgems: 1790,
          isOpen: true,
          picture: '953.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 219,
          clubId: 32,
          nickname: 'Франк',
          stars: 3,
          power: 58,
          costcoins: 10320,
          ismarket: true,
          costgems: 1790,
          isOpen: true,
          picture: '219.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 127,
          clubId: 32,
          nickname: 'Том',
          stars: 3,
          power: 50,
          costcoins: 4000,
          ismarket: true,
          costgems: 1790,
          isOpen: true,
          picture: '127.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2029,
          clubId: 32,
          nickname: 'YungBull',
          stars: 3,
          power: 70,
          costcoins: 10800,
          ismarket: false,
          costgems: 1790,
          isOpen: false,
          picture: '2029.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1114,
          clubId: 32,
          nickname: 'Цыпа',
          stars: 4,
          power: 53,
          costcoins: 60720,
          ismarket: true,
          costgems: 4690,
          isOpen: true,
          picture: '1114.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1090,
          clubId: 32,
          nickname: 'РусКор',
          stars: 3,
          power: 40,
          costcoins: 4000,
          ismarket: true,
          costgems: 1790,
          isOpen: true,
          picture: '1090.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2494,
          clubId: 32,
          nickname: 'Статистика',
          stars: 2,
          power: 40,
          costcoins: 2000,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          picture: '2494.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2647,
          clubId: 32,
          nickname: 'MUR',
          stars: 2,
          power: 41,
          costcoins: 2000,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          picture: '2647.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1373,
          clubId: 32,
          nickname: 'ZHIREKTOR',
          stars: 3,
          power: 55,
          costcoins: 10200,
          ismarket: true,
          costgems: 1790,
          isOpen: true,
          picture: '1373.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 330,
          clubId: 32,
          nickname: 'Зажигалочка',
          stars: 2,
          power: 58,
          costcoins: 5160,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          picture: '330.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 289,
          clubId: 32,
          nickname: 'Лис',
          stars: 3,
          power: 54,
          costcoins: 10160,
          ismarket: true,
          costgems: 1790,
          isOpen: true,
          picture: '289.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 5060,
          clubId: 32,
          nickname: 'Blizzard',
          stars: 2,
          power: 46,
          costcoins: 2000,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          picture: '5060.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 799,
          clubId: 32,
          nickname: 'Лирика',
          stars: 2,
          power: 58,
          costcoins: 5160,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          picture: '799.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2022,
          clubId: 32,
          nickname: 'Мол4ун',
          stars: 3,
          power: 48,
          costcoins: 4000,
          ismarket: true,
          costgems: 1790,
          isOpen: true,
          picture: '2022.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 148,
          clubId: 32,
          nickname: 'Давид',
          stars: 2,
          power: 52,
          costcoins: 5040,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          picture: '148.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 337,
          clubId: 32,
          nickname: 'Весна',
          stars: 2,
          power: 50,
          costcoins: 2000,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          picture: '337.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 227,
          clubId: 32,
          nickname: 'Freedom',
          stars: 3,
          power: 52,
          costcoins: 10080,
          ismarket: true,
          costgems: 1790,
          isOpen: true,
          picture: '227.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 7719,
          clubId: 32,
          nickname: 'vitya061',
          stars: 1,
          power: 51,
          costcoins: 2510,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '7719.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1352,
          clubId: 32,
          nickname: 'Слепой Часовщик',
          stars: 2,
          power: 40,
          costcoins: 2000,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          picture: '1352.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2365,
          clubId: 32,
          nickname: 'ТП',
          stars: 2,
          power: 47,
          costcoins: 2000,
          ismarket: false,
          costgems: 899,
          isOpen: false,
          picture: '2365.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1773,
          clubId: 32,
          nickname: 'Русалка',
          stars: 2,
          power: 44,
          costcoins: 2000,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          picture: '1773.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 230,
          clubId: 32,
          nickname: 'День',
          stars: 1,
          power: 40,
          costcoins: 1000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          picture: '230.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1361,
          clubId: 32,
          nickname: 'Natumba',
          stars: 2,
          power: 41,
          costcoins: 2000,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          picture: '1361.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1362,
          clubId: 32,
          nickname: 'Ricci',
          stars: 1,
          power: 43,
          costcoins: 1000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '1362.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 6359,
          clubId: 32,
          nickname: 'Энакин',
          stars: 1,
          power: 40,
          costcoins: 1000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '6359.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 3197,
          clubId: 32,
          nickname: 'Kenpachi',
          stars: 3,
          power: 45,
          costcoins: 4000,
          ismarket: false,
          costgems: 1790,
          isOpen: false,
          picture: '3197.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 228,
          clubId: 32,
          nickname: 'Нежный лосось',
          stars: 2,
          power: 48,
          costcoins: 2000,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          picture: '228.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 240,
          clubId: 32,
          nickname: 'Синичкин',
          stars: 1,
          power: 29,
          costcoins: 1000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          picture: '240.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 290,
          clubId: 32,
          nickname: 'Priss',
          stars: 1,
          power: 40,
          costcoins: 1000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          picture: '290.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 292,
          clubId: 32,
          nickname: 'Алпат',
          stars: 1,
          power: 30,
          costcoins: 1000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          picture: '292.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 294,
          clubId: 32,
          nickname: 'plohoy paren',
          stars: 2,
          power: 46,
          costcoins: 2000,
          ismarket: false,
          costgems: 899,
          isOpen: false,
          picture: '294.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1077,
          clubId: 32,
          nickname: 'Пешмерга',
          stars: 2,
          power: 28,
          costcoins: 2000,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          picture: '1077.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1082,
          clubId: 32,
          nickname: 'Студень',
          stars: 2,
          power: 44,
          costcoins: 2000,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          picture: '1082.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1110,
          clubId: 32,
          nickname: 'Ассоль',
          stars: 1,
          power: 41,
          costcoins: 1000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '1110.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1128,
          clubId: 32,
          nickname: 'Понч',
          stars: 1,
          power: 52,
          costcoins: 2520,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '1128.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1369,
          clubId: 32,
          nickname: 'Персик RE',
          stars: 1,
          power: 37,
          costcoins: 1000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '1369.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1640,
          clubId: 32,
          nickname: 'Заварка',
          stars: 1,
          power: 30,
          costcoins: 1000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          picture: '1640.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1907,
          clubId: 32,
          nickname: 44,
          stars: 2,
          power: 42,
          costcoins: 2000,
          ismarket: true,
          costgems: 899,
          isOpen: true,
          picture: '1907.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2625,
          clubId: 32,
          nickname: '13,',
          stars: 1,
          power: 41,
          costcoins: 1000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '2625.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 4049,
          clubId: 32,
          nickname: 'Ромео',
          stars: 1,
          power: 29,
          costcoins: 1000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '4049.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 226,
          clubId: 32,
          nickname: 'Левша',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '226.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 241,
          clubId: 32,
          nickname: 'Fas1k',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '241.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 505,
          clubId: 32,
          nickname: 'Арчер',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          picture: '505.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 770,
          clubId: 32,
          nickname: 'Картузо',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '770.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 861,
          clubId: 32,
          nickname: ',',
          stars: 2,
          power: 0,
          costcoins: 2000,
          ismarket: false,
          costgems: 899,
          isOpen: false,
          picture: '861.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1426,
          clubId: 32,
          nickname: 'Pavlina',
          stars: 1,
          power: 51,
          costcoins: 2510,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '1426.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1444,
          clubId: 32,
          nickname: 'London',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: true,
          costgems: 449,
          isOpen: true,
          picture: '1444.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1487,
          clubId: 32,
          nickname: 'Скарлет',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '1487.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 1792,
          clubId: 32,
          nickname: 'Пушистик',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '1792.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2620,
          clubId: 32,
          nickname: 'Фрэнки',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '2620.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2643,
          clubId: 32,
          nickname: 'Борисов',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '2643.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 2832,
          clubId: 32,
          nickname: 'Ханова',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '2832.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 4602,
          clubId: 32,
          nickname: 'Аслан',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '4602.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gomafiaId: 7115,
          clubId: 32,
          nickname: 'Mortal',
          stars: 1,
          power: 0,
          costcoins: 1000,
          ismarket: false,
          costgems: 449,
          isOpen: false,
          picture: '7115.png',
          cityId: 1,
          countryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    );
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('Players', null, {});
  },
};
