'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Items',
      [
        {
          type: 'Ускоритель тренировки',
          grade: null,
          costgems: 3,
          name: 'Ускорение 1 минута',
          effect: 'Снижает время необходимое на тренировку на 1 минуту',
          picture: '',
          actionName: 'addTime',
          timeAdd: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          type: 'Ускоритель тренировки',
          grade: null,
          costgems: 40,
          name: 'Ускорение 15 минут',
          effect: 'Снижает время необходимое на тренировку на 15 минут',
          picture: '',
          actionName: 'addTime',
          timeAdd: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          type: 'Ускоритель тренировки',
          grade: null,
          costgems: 120,
          name: 'Ускорение 60 минут',
          effect: 'Снижает время необходимое на тренировку на 1 час',
          picture: '',
          actionName: 'addTime',
          timeAdd: 60,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          type: 'Ускоритель тренировки',
          grade: null, 
          costgems: 300,
          name: 'Ускорение 3 часа',
          effect: 'Снижает время необходимое на тренировку на 3 часа',
          picture: '',
          actionName: 'addTime',
          timeAdd: 180,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          type: 'Ускоритель тренировки',
          grade: null,
          costgems: 600,
          name: 'Ускорение 8 часов',
          effect: 'Снижает время необходимое на тренировку на 8 часов',
          picture: '',
          actionName: 'addTime',
          timeAdd: 480,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          type: 'Ускоритель тренировки',
          grade: null,
          costgems: 1000,
          name: 'Ускорение 15 часов',
          effect: 'Снижает время необходимое на тренировку на 15 часов',
          picture: '',
          actionName: 'addTime',
          timeAdd: 720,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          type: 'Ускоритель тренировки',
          grade: null,
          costgems: 1500,
          name: 'Ускорение 24 часа',
          effect: 'Снижает время необходимое на тренировку на 24 часа',
          picture: '',
          actionName: 'addTime',
          timeAdd: 1440,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          type: 'Ускоритель тренировки',
          grade: null,
          costgems: 4400,
          name: 'Ускорение 3 дня',
          effect: 'Снижает время необходимое на тренировку на 3 дня',
          picture: '',
          actionName: 'addTime',
          timeAdd: 4320,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          type: 'Ускоритель тренировки',
          grade: null,
          costgems: 10000,
          name: 'Ускорение 7 дней',
          effect: 'Снижает время необходимое на тренировку на 7 дней',
          picture: '',
          actionName: 'addTime',
          timeAdd: 10080,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          type: 'Ускоритель тренировки',
          grade: null,
          costgems: 40000,
          name: 'Ускорение 30 дней',
          effect: 'Снижает время необходимое на тренировку на 30 дней',
          picture: '',
          actionName: 'addTime',
          timeAdd: 43200,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          type: 'Пробная карта',
          grade: 5,
          costgems: 10,
          name: 'Пробная карта Градиент',
          effect: 'Вы получаете в ваше распоряжение спортсмена на один турнир',
          picture: '',
          actionName: 'rentPlayer',
          duration: 1440,
          playerId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          type: 'Wild card',
          grade: 10,
          name: 'Обычная wild card',
          effect: 'Вы получаете обычного спортсмена по выбору навсегда',
          picture: '',
          actionName: 'giftPlayer',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          type: 'Wild card',
          grade: 20,
          name: 'Опытная wild card',
          effect: 'Вы получаете опытного спортсмена по выбору навсегда',
          picture: '',
          actionName: 'giftPlayer',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          type: 'Wild card',
          grade: 30,
          name: 'Элитная wild card',
          effect: 'Вы получаете элитного спортсмена по выбору навсегда',
          picture: '',
          actionName: 'giftPlayer',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          type: 'Wild card',
          grade: 40,
          name: 'Топовая wild card',
          effect: 'Вы получаете топового спортсмена по выбору навсегда',
          picture: '',
          actionName: 'giftPlayer',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          type: 'Wild card',
          grade: 50,
          name: 'Легендарная wild card',
          effect: 'Вы получаете легендарного спортсмена по выбору навсегда',
          picture: '',
          actionName: 'giftPlayer',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Item', null, {});
  },
};
